language: node_js

node_js:
  - '5.1'

cache:
  directories:
    - node_modules

install:
  - npm install -g codeclimate-test-reporter
  - npm install

script:
  - npm test

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
