name: Build App

on: [push, pull_request]

jobs:
  build-macos:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Make macOS (electron-builder)
        env:
          CSC_LINK: ${{ secrets.mac_certs }}
          CSC_KEY_PASSWORD: ${{ secrets.mac_certs_password }}
        run: yarn make:macos -c.mac.identity=null

      - name: Clean up builds
        run: rm -rfv dist/mac

      - uses: actions/upload-artifact@v1
        with:
          name: Gitify-dist
          path: dist

  build-win-windows:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Make Windows (electron-builder)
        env:
        run: yarn make:win

      - name: Clean up builds
        run: rm -rfv dist/mac

      - uses: actions/upload-artifact@v1
        with:
          name: Gitify-dist
          path: dist
