name: Release App

on:
  push:
    branches:
      - release

jobs:
  release-macos:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Pack (electron-builder)
        run: yarn pack

      - name: Publish macOS (electron-builder)
        env:
          CSC_LINK: ${{ secrets.mac_certs }}
          CSC_KEY_PASSWORD: ${{ secrets.mac_certs_password }}
          GH_TOKEN: ${{ secrets.gh_token }}
        run: yarn electron-builder --publish onTagOrDraft
